name: fl_business_card
description: Open-source & serverless Business Card generator, made with
  Flutter, for Mobile.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  fl_business_card_core:
    git:
      url: https://github.com/Floating-Dartists/fl_business_card_core.git
      ref: 0.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  font_awesome_flutter: ^9.2.0
  go_router: ^3.0.2
  google_fonts: ^2.3.1
  hive_flutter: ^1.1.0

dev_dependencies:
  alchemist: ^0.3.2
  device_sizes:
    git:
      url: https://github.com/matthew-carroll/device_sizes.git
      ref: main
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  mocktail: ^0.3.0
  remove_from_coverage: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
